# Generated by Django 6.0.3 on 2026-04-07 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('active_ingredient', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=50, null=True)),
                ('form', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('conflicts_with', models.TextField(null=True)),
                ('interaction_severity', models.CharField(max_length=20, null=True)),
                ('interaction_description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Medicine_Catalog',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Device_Tokens',
            },
        ),
        migrations.CreateModel(
            name='UserMedicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=50, null=True)),
                ('instructions', models.CharField(max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('duration_type', models.CharField(max_length=20, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_day', models.TimeField()),
                ('repeat_type', models.CharField(max_length=20, null=True)),
                ('days_of_week', models.CharField(max_length=50, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermedicine')),
            ],
            options={
                'db_table': 'Medicine_Schedule',
            },
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermedicine')),
            ],
            options={
                'db_table': 'Dose_Logs',
            },
        ),
    ]
